#!/bin/sh

NVCHAD_APP_NAME=NvChad
NVCHAD_APP_CONFIG=~/.config/$NVCHAD_APP_NAME
export NVCHAD_APP_NAME NVCHAD_APP_CONFIG

rm -rf $NVCHAD_APP_CONFIG && mkdir -p $NVCHAD_APP_CONFIG

stow --restow --target=$NVCHAD_APP_CONFIG .

alias nvchad="NVIM_APPNAME=$NVCHAD_APP_NAME nvim"
